### ISSUE TITLE
Issue with some fonts and images in css

### ISSUE THREAD

**Issue by ArmorDarks** [hollandben/grunt-cache-bust#112]
Hi

First of all, thanks for the great plugin!

I'm not sure, but it seems to be some issue with parsing of font-face declaration and images

For instance, we have following task:

``` coffee
module.exports = ->
  @config 'cacheBust',
    build:
      options:
        algorithm: 'md5'
        deleteOriginals: true
        baseDir: '<%= path.build.root %>'
      files: [
        src: [
          '<%= path.build.root %>/{,**/}*.html',
          '<%= path.build.root %>/{,**/}*.css'
        ]
      ]
```

following css:

```
@font-face {
  font-family:icons;
  src:url(/assets/fonts/icons.eot);
  src:url(/assets/fonts/icons.eot#iefix) format(embedded-opentype),
      url(/assets/fonts/icons.woff) format(woff),
      url(/assets/fonts/icons.ttf) format(truetype);
  font-weight:400;
  font-style:normal;
}

.sprite {
  background:url(/assets/sprites/sprite.png) no-repeat;
}
```

This will produce:

Fonts file-names like those:

```
icons.f1d05013cb3afab0.eot
icons.ttf
icons.woff
```

Spirte file-name like that:

```
sprite.dfa1acde53d18b33.png
```

And following css:

``` css
@font-face {
  font-family:icons;
  src:url(/assets/fonts/icons.f1d05013cb3afab0.eot);
  src:url(/assets/fonts/icons.f1d05013cb3afab0.eot#iefix) format(embedded-opentype),
      url(/assets/fonts/icons.woff) format(woff),
      url(/assets/fonts/icons.ttf) format(truetype);
  font-weight:400;
  font-style:normal;
}

.sprite {
  background:url(/assets/sprites/sprite.png) no-repeat;
}
```

Notice that `ttf` and `woff` didn't receive proper names. It seems that it somehow related to the fact that they are defined in `@font-face` declaration by using comma.

Also you can notice that sprite url in CSS declaration wasn't updated for some reason.

If we'll call css `src` before html, like that:

``` coffee
module.exports = ->
  @config 'cacheBust',
    build:
      options:
        # @todo Enable length option when PR with fix will be merged
        # length: 6
        algorithm: 'md5'
        deleteOriginals: true
        baseDir: '<%= path.build.root %>'
      files: [
        src: [
          '<%= path.build.root %>/{,**/}*.css',
          '<%= path.build.root %>/{,**/}*.html'
        ]
      ]
```

it will fix issue with not updated url in `.sprite` selector for some reason, but it's seems to be like wrong behavior — shouldn't result be same, regardless of the order?

It, of course, also doesn't fix issue with `@font-face` declaration.

Thanks in advance
