### ISSUE TITLE
woff2 fonts are not hashed at all

### ISSUE THREAD

**Issue by thrawn-sh** [hollandben/grunt-cache-bust#143]
I'm using Material Design Icons (https://materialdesignicons.com) for my project, the css includes the following font-face definition:

```css
@font-face {
  font-family: 'MaterialDesignIcons';
  src: url("../fonts/materialdesignicons-webfont.eot?v=1.1.34");
  src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=1.1.34") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=1.1.34") format("woff2"), url+("../fonts/materialdesignicons-webfont.woff?v=1.1.34") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=1.1.34") format("truetype"), url("../fonts/materialdesignic+ons-webfont.svg?v=1.1.34#materialdesigniconsregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

The woff, svg, eot and ttf files are handled correctly, the woff2 are not handled correctly. The woff2 reference gets substituded with a hashed reference, but the file is not renamed in the file system. My cache-bust config is the following:

```javascript
cacheBust: {
            options: {
                algorithm: "md5",
                deleteOriginals: true,
                ignorePatterns: ["android-chrome", "apple-touch-icon", "favicon"],
                length: 32,
                removeUrlFragmentHint: true,
                rename: true,
            },
            assets: {
                files: [
                    { src: ["dist/**/*.css"] , filter: "isFile" },
                    { src: ["dist/**/*.js"]  , filter: "isFile" },
                    { src: ["dist/**/*.html"], filter: "isFile" },
                ],
            },
},
```
